### ISSUE TITLE
Migraton V1 -> v2

### ISSUE THREAD

**Issue by Fabrice-Fabio** [0xsquid/squid-sdk#282]
I was on a react (cra) v4 version which I migrated to V5 so that it was compatible with version 2.8.9 of @0xsquid/sdk.
Once react migration from v4 to "react-scripts": "5.0.1"
However I get this error after making all the changes advised in the documentation for the migration from V1 to V2 : [Docs](https://docs.squidrouter.com/squid-v1-docs-cosmos/v1-greater-than-v2-migration).

I initialize squid like this:
`const squid = new Squid({ baseUrl: 'https://v2.api.squidrouter.com', integratorId: "My-key" });
`

With "ethers": "^5.7.2",
> tokenList.jsx:38 Uncaught TypeError: _0xsquid_sdk_dist_types__WEBPACK_IMPORTED_MODULE_3__.Squid is not a constructor

Then when i change the version of "ethers" to "^6.7.1" like mention on the documentation i got those errors : 

> Uncaught Error: Cannot find module 'ethers/lib/utils.js'
>     at webpackMissingModule

Need help and more clarification on this error please.

**Comment by 0x0Koda** [comment]
Who had raised this issue?
